from django.urls import path
from asp import views

urlpatterns = [
	path('clinic_manager/<int:id>/home/<int:category>',
		views.CMViewItems.as_view(),
		name='clinic_manager-home'),
	path('clinic_manager/item_info/<int:id>',
		views.CMViewItemInfo.as_view()),
	path('clinic_manager/construct_order', 
		views.CMConstructOrder.as_view(), 
		name='constructOrder'),
	path('clinic_manager/<int:id>/view_order',
		views.CMViewOrder.as_view(),
		name='clinic_manager-view_order'),
	path('dispatcher/home',
		views.DispatcherViewQueue.as_view(),
		name='dispatcher-home'),
	path('dispatcher/dispatch_order',
		views.DispatcherViewPackage.as_view(),
		name='dispatcher-package'),
	path('dispatcher/generate_csv',
		views.DispatcherViewItinerary.as_view(),
		name='dispatcher-itinerary'),
	path('dispatcher/confirm_dispatch',
		views.DispatcherConfirmDispatch.as_view(),
		name='dispatcher-confirm'),
	path('status_change_to/qfd/<int:orderid>',
		views.ChangeStatus.toQFD(),
		name='change-status-to-qfd'),
	path('status_change_to/di/<int:orderid>',
		views.ChangeStatus.toDI(),
		name='change-status-to-di'),
	path('status_change_to/de/<int:orderid>',
		views.ChangeStatus.toDE(),
		name='change-status-to-de'),
	path('status_change_to/ca/<int:orderid>',
		views.ChangeStatus.toCA(),
		name='change-status-to-ca')
]