# Generated by Django 2.1.3 on 2018-11-04 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0002_auto_20181104_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='manager_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manager_id', to='asp.User'),
            preserve_default=False,
        ),
    ]
