# Generated by Django 2.1.3 on 2018-11-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0005_auto_20181104_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='canceled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='dilivered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='dispatching_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='processing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
