# Generated by Django 2.1.3 on 2018-11-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0006_auto_20181104_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercontainsitem',
            name='item_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
